### ISSUE TITLE
Number argument of random string resource is deprecated

### ISSUE THREAD

**Issue by Young-ook** [Young-ook/terraform-aws-vpc#6]
Warning: Argument is deprecated
│
│   with module.vpc.random_string.uid,
│   on .terraform/modules/vpc/labels.tf line 5, in resource "random_string" "uid":
│    5:   number  = false
│
│ Use numeric instead.

**Comment by cyb3ralbert** [comment]
Hi there! Accordingly to a fresh documentation here:

https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string
```
NOTE: This is deprecated, use numeric instead.

```
